version: "3"
service:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    envinronment:
      MYSQL_ROOT_PASSWORD: "Admin123"
      MYSQL_DATADASE: "hex_test"
    volumes:
      - ./testdb/:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    
grpc:
  build: .
  envinronment:
    DB_DRIVER: "mysql"
    DB_DSN: "root:Admin123@tcp(db:3306)/hex_test"
  depends:
    - db
  command: ["go, test, -v, './...'"]